networks:
  1panel-network:
    external: true
services:
  cli-proxy-api:
    image: rizxfrog/cli-proxy-api:latest
    container_name: cli-proxy-api
    networks:
      - 1panel-network
    env_file:
      - .env
    ports:
      - "8317:8317"
    volumes:
      - ./data:/CLIProxyAPI/data
      - ./config.yaml:/CLIProxyAPI/config.yaml
#      - ${AUTH_DIR_PATH}:/CLIProxyAPI/data/auth_files
#      - ${PLUGIN_DIR_PATH:-./plugins}:/CLIProxyAPI/plugins
    environment:
      TZ: Asia/Shanghai
#      MANAGEMENT_STATIC_PATH:
      MODELS_FILE: /CLIProxyAPI/data/models.json
      DEPLOY: ${DEPLOY:-}
      WRITABLE_PATH: /CLIProxyAPI/data/front
    restart: unless-stopped
